AWSTemplateFormatVersion: '2010-09-09'
Description: 'This Lambda will modify the RDS Instance based on the input from Event Triggers'
Parameters:
  Name:
    Description: Name of the project
    Type: String
    Default: project-name
  Bucket:
    Description: Bucket for lambda artifact
    Type: String
  Environment:
    Type: String
    Default: dev
    Description: Environment name
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: Must be one of dev, test, or prod
  LambdaArtifact:
    Type: String
    Description: Name of file that contains lambda code
    Default: lambda_function.zip
  AwsAccountInfoLambda:
    Type: String
    Description: VPC info lambda function
    Default: aws-account-info
Resources:
  AwsInfo:
    Type: Custom::AwsInfo
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AwsAccountInfoLambda}'
  Role:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/GithubActionsIamResourcePermissionsBoundary'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
      - PolicyName: !Sub ${Environment}-${Name}-policy
        PolicyDocument:
          Statement:
            - Sid: RDSperms
              Effect: Allow
              Action:
                - rds:DescribeDBInstances
                - rds:DescribeDBClusterEndpoints
                - rds:StartDBCluster
                - rds:StopDBCluster
                - rds:StopDBInstance
                - rds:StartDBInstance
                - rds:RebootDBInstance
                - rds:CreateDBCluster
                - rds:CreateDBInstance
                - rds:ModifyDBInstance
                - rds:ModifyDBCluster
                - rds:DeleteDBInstance
                - rds:DeleteDBCluster
              Resource:
                - '*'
      RoleName: !Sub ${Environment}-${Name}
      Tags:
      - Key: "ALLOW_GHA_DELETE"
        Value: "TRUE"
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: ' '
      FunctionName: !Sub ${Environment}-${Name}
      Handler: 'core_forecast_rds_modification.lambda_function.lambda_handler'
      MemorySize: 512
      Timeout: 300
      Code:
        S3Bucket: !Ref 'Bucket'
        S3Key: !Ref 'LambdaArtifact'
      Role: !GetAtt 'Role.Arn'
      Runtime: python3.8
      Environment:
        Variables:
          ENV: !Ref 'Environment'
